export const LANGUAGES = [
  { value: "ro", label: "Romanian" },
  { value: "eng", label: "English" },
  { value: "spa", label: "Spanish" },
  { value: "fra", label: "French" },
  { value: "deu", label: "German" },
  { value: "ita", label: "Italian" },
  { value: "por", label: "Portuguese" },
  { value: "nld", label: "Dutch" },
  { value: "rus", label: "Russian" },
  { value: "pol", label: "Polish" },
  { value: "tur", label: "Turkish" },
  { value: "ara", label: "Arabic" },
  { value: "zho", label: "Chinese" },
  { value: "jpn", label: "Japanese" },
  { value: "kor", label: "Korean" },
  { value: "hin", label: "Hindi" },
  { value: "swe", label: "Swedish" },
  { value: "dan", label: "Danish" },
  { value: "fin", label: "Finnish" },
  { value: "nor", label: "Norwegian" },
  { value: "hun", label: "Hungarian" },
  { value: "ces", label: "Czech" },
  { value: "ell", label: "Greek" },
  { value: "bul", label: "Bulgarian" },
  { value: "ukr", label: "Ukrainian" },
  { value: "heb", label: "Hebrew" },
] as const;
