"""rely_on_base_user_table_for_bools

Revision ID: 03cc263fdbf7
Revises: 5c386c03a5e8
Create Date: 2025-05-17 20:20:50.904502

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03cc263fdbf7"
down_revision: str | None = "5c386c03a5e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_jobs_user_id_users", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_jobs_user_id_users"), "users", ["user_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=50),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=50),
            server_default=sa.text("'standard'::character varying"),
            existing_nullable=False,
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_jobs_user_id_users"), type_="foreignkey")
        batch_op.create_foreign_key("fk_jobs_user_id_users", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###
