"""Add validation status fields to app_settings

Revision ID: 14ce5e28840f
Revises: c6a393b59004
Create Date: 2025-12-22 10:12:00.782187

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14ce5e28840f"
down_revision: str | None = "c6a393b59004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with server_default for existing rows
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tmdb_valid", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column("omdb_valid", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column(
                "opensubtitles_valid", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("opensubtitles_valid")
        batch_op.drop_column("omdb_valid")
        batch_op.drop_column("tmdb_valid")

    # ### end Alembic commands ###
