"""Add app_settings table

Revision ID: 1b0caf6177e4
Revises: 88fbd64e1c24
Create Date: 2025-12-21 09:58:00.249172

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b0caf6177e4"
down_revision: str | None = "88fbd64e1c24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tmdb_api_key", sa.Text(), nullable=True),
        sa.Column("omdb_api_key", sa.Text(), nullable=True),
        sa.Column("opensubtitles_api_key", sa.Text(), nullable=True),
        sa.Column("opensubtitles_username", sa.Text(), nullable=True),
        sa.Column("opensubtitles_password", sa.Text(), nullable=True),
        sa.Column("deepl_api_keys", sa.Text(), nullable=True),
        sa.Column("qbittorrent_host", sa.String(length=255), nullable=True),
        sa.Column("qbittorrent_port", sa.Integer(), nullable=True),
        sa.Column("qbittorrent_username", sa.String(length=255), nullable=True),
        sa.Column("qbittorrent_password", sa.Text(), nullable=True),
        sa.Column("allowed_media_folders", sa.Text(), nullable=True),
        sa.Column("setup_completed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_settings")
    # ### end Alembic commands ###
