"""add_dashboard_tiles

Revision ID: 22f7ebddb421
Revises: initial_schema.py
Create Date: 2025-12-20 09:32:10.047341

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22f7ebddb421"
down_revision: str | None = "initial_schema.py"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_tiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_tiles")),
    )
    with op.batch_alter_table("dashboard_tiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dashboard_tiles_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dashboard_tiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dashboard_tiles_id"))

    op.drop_table("dashboard_tiles")
    # ### end Alembic commands ###
