"""Add login_attempts table for account lockout

Revision ID: 283a7cf6dda8
Revises: 9f3e2c1a4b57
Create Date: 2025-12-29 21:36:33.597536

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "283a7cf6dda8"
down_revision: str | None = "9f3e2c1a4b57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_login_attempts_attempted_at"), ["attempted_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_login_attempts_email"), ["email"], unique=False)
        batch_op.create_index(
            "ix_login_attempts_email_attempted", ["email", "attempted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_login_attempts_ip_address"), ["ip_address"], unique=False
        )
        batch_op.create_index(
            "ix_login_attempts_ip_attempted", ["ip_address", "attempted_at"], unique=False
        )

    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.alter_column(
            "use_count", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.alter_column(
            "use_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("0"),
            existing_nullable=False,
        )

    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_login_attempts_ip_attempted")
        batch_op.drop_index(batch_op.f("ix_login_attempts_ip_address"))
        batch_op.drop_index("ix_login_attempts_email_attempted")
        batch_op.drop_index(batch_op.f("ix_login_attempts_email"))
        batch_op.drop_index(batch_op.f("ix_login_attempts_attempted_at"))

    op.drop_table("login_attempts")
    # ### end Alembic commands ###
