"""Add output_file_path to translation_log

Revision ID: 2a0d9e2a0add
Revises: 94c7d4638a88
Create Date: 2025-12-22 15:35:11.859971

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a0d9e2a0add"
down_revision: str | None = "94c7d4638a88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("translation_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("output_file_path", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("translation_log", schema=None) as batch_op:
        batch_op.drop_column("output_file_path")

    # ### end Alembic commands ###
