"""Add Google usage columns

Revision ID: 3d8d55585c60
Revises: e51f74fe569f
Create Date: 2025-12-27 23:31:22.239279

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d8d55585c60"
down_revision: str | None = "e51f74fe569f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("google_usage_total_chars", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("google_usage_month_chars", sa.BigInteger(), nullable=True))
        batch_op.add_column(
            sa.Column("google_usage_last_updated", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("google_usage_last_updated")
        batch_op.drop_column("google_usage_month_chars")
        batch_op.drop_column("google_usage_total_chars")

    # ### end Alembic commands ###
