"""add_opensubtitles_subscription_info

Revision ID: 5d4307a95cfb
Revises: 0dd875e71ee0
Create Date: 2025-12-27 20:17:21.567697

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d4307a95cfb"
down_revision: str | None = "0dd875e71ee0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("opensubtitles_level", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("opensubtitles_vip", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("opensubtitles_allowed_downloads", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("opensubtitles_rate_limited", sa.Boolean(), nullable=True))
        batch_op.alter_column(
            "tmdb_valid", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=True
        )
        batch_op.alter_column(
            "omdb_valid", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=True
        )
        batch_op.alter_column(
            "opensubtitles_valid",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.alter_column(
            "opensubtitles_valid",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "omdb_valid",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "tmdb_valid",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=True,
        )
        batch_op.drop_column("opensubtitles_rate_limited")
        batch_op.drop_column("opensubtitles_allowed_downloads")
        batch_op.drop_column("opensubtitles_vip")
        batch_op.drop_column("opensubtitles_level")

    # ### end Alembic commands ###
