"""Add user preferences

Revision ID: 690ef37d906e
Revises: c683232956e2
Create Date: 2025-12-30 03:07:48.532565

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "690ef37d906e"
down_revision: str | None = "c683232956e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("preferences", sa.JSON(), nullable=True))
        batch_op.alter_column(
            "force_password_change",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "force_password_change",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=False,
        )
        batch_op.drop_column("preferences")

    # ### end Alembic commands ###
