"""add_log_level_to_jobs

Revision ID: 7f55fc09b636
Revises: 22f7ebddb421
Create Date: 2025-12-20 19:08:17.293090

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f55fc09b636"
down_revision: str | None = "22f7ebddb421"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # First add column as nullable with server default
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("log_level", sa.String(length=10), nullable=False, server_default="INFO")
        )

    # Remove the server default (optional - keep if you want DB-level default)
    # with op.batch_alter_table('jobs', schema=None) as batch_op:
    #     batch_op.alter_column('log_level', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("log_level")

    # ### end Alembic commands ###
