"""Fix storage paths created_at default

Revision ID: 88fbd64e1c24
Revises: be9a77b67976
Create Date: 2025-12-20 23:08:55.863874

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # For explicit ENUM drop

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88fbd64e1c24"
down_revision: str | None = "be9a77b67976"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_paths", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_paths", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###
