"""create_users_and_jobs_tables_and_enum # Changed description

Revision ID: 8c37df51f001
Revises:
Create Date: 2025-05-07 12:22:24.069058

"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy  # <<< --- FIX 1: ADDED IMPORT
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # <<< For explicit ENUM drop if needed

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c37df51f001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("role", sa.String(length=20), server_default="standard", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),  # Added server_default to match model
        # FIX 2: Added server_default and default to is_superuser
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            default=False,
        ),
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),  # Added server_default to match model
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)

    # Define job_status_enum explicitly for clarity and use in downgrade
    job_status_enum_type = sa.Enum(
        "PENDING",
        "RUNNING",
        "SUCCEEDED",
        "FAILED",
        "CANCELLED",
        name="job_status_enum",
        inherit_schema=True,
    )
    # This line is not strictly needed if the type is created via the column def,
    # but ensures it exists. create_type=True in the model does this.
    # If using SQLAlchemyEnum from model with create_type=True, this might be redundant or handled by the column.
    # For safety, let's assume the column definition handles creation.

    op.create_table(
        "jobs",
        sa.Column(
            "id", postgresql.UUID(as_uuid=True), nullable=False
        ),  # Used postgresql.UUID for consistency
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("folder_path", sa.String(length=1024), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("status", job_status_enum_type, nullable=False),  # Use the defined type
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # Added server_default
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_message", sa.Text(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("log_snippet", sa.Text(), nullable=True),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_jobs_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_celery_task_id"), ["celery_task_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_user_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_celery_task_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")

    # FIX 3: Explicitly drop the enum type
    job_status_enum_type = postgresql.ENUM(
        "PENDING",
        "RUNNING",
        "SUCCEEDED",
        "FAILED",
        "CANCELLED",
        name="job_status_enum",
        inherit_schema=True,
    )
    job_status_enum_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
