"""Add tmdb_rate_limited column

Revision ID: 8ca55a47da71
Revises: 6d9a31d887d6
Create Date: 2025-12-27 19:05:49.942079

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ca55a47da71"
down_revision: str | None = "6d9a31d887d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tmdb_rate_limited", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("tmdb_rate_limited")

    # ### end Alembic commands ###
