"""Add translation_log table and google cloud fields

Revision ID: 94c7d4638a88
Revises: 73f12ec5f64c
Create Date: 2025-12-22 15:07:13.454724

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94c7d4638a88"
down_revision: str | None = "73f12ec5f64c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translation_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("source_language", sa.String(length=10), nullable=True),
        sa.Column("target_language", sa.String(length=10), nullable=False),
        sa.Column("service_used", sa.String(length=50), nullable=False),
        sa.Column("characters_billed", sa.Integer(), nullable=False),
        sa.Column("deepl_characters", sa.Integer(), nullable=False),
        sa.Column("google_characters", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_translation_log")),
    )
    with op.batch_alter_table("translation_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_translation_log_timestamp"), ["timestamp"], unique=False
        )

    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("google_cloud_credentials", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("google_cloud_project_id", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("google_cloud_valid", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("google_cloud_valid")
        batch_op.drop_column("google_cloud_project_id")
        batch_op.drop_column("google_cloud_credentials")

    with op.batch_alter_table("translation_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_translation_log_timestamp"))

    op.drop_table("translation_log")
    # ### end Alembic commands ###
