"""Make validation status fields nullable

Revision ID: b42ce73310e5
Revises: 14ce5e28840f
Create Date: 2025-12-22 10:23:35.861535

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b42ce73310e5"
down_revision: str | None = "14ce5e28840f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.alter_column("tmdb_valid", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("omdb_valid", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("opensubtitles_valid", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.alter_column("opensubtitles_valid", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("omdb_valid", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("tmdb_valid", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###
