"""Add storage paths

Revision ID: be9a77b67976
Revises: 7f55fc09b636
Create Date: 2025-12-20 23:00:59.050015

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be9a77b67976"
down_revision: str | None = "7f55fc09b636"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_paths",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_paths")),
    )
    with op.batch_alter_table("storage_paths", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_storage_paths_path"), ["path"], unique=True)

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "log_level",
            existing_type=sa.VARCHAR(length=10),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "log_level",
            existing_type=sa.VARCHAR(length=10),
            server_default=sa.text("'INFO'::character varying"),
            existing_nullable=False,
        )

    with op.batch_alter_table("storage_paths", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_storage_paths_path"))

    op.drop_table("storage_paths")
    # ### end Alembic commands ###
