"""enhanced_audit_schema_and_rls

Revision ID: c2a670635b4d
Revises: e4e7e3a83c68
Create Date: 2026-01-05 16:41:55.183649

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2a670635b4d"
down_revision: str | None = "e4e7e3a83c68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Alter main audit_logs table (Postgres handles propagation to partitions)
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("impersonator_id", sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column("request_method", sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column("request_path", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("outcome", sa.String(length=20), server_default="success", nullable=False)
        )
        batch_op.add_column(sa.Column("reason_code", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("service_version", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("environment", sa.String(length=20), nullable=True))

        # Remove server defaults after adding (optional, but requested by autogen)
        batch_op.alter_column("outcome", server_default=None)

        batch_op.alter_column(
            "severity",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "success", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "actor_type",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "source",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "schema_version",
            existing_type=sa.SMALLINT(),
            server_default=None,
            existing_nullable=False,
        )

        batch_op.create_index(
            batch_op.f("ix_audit_logs_impersonator_id"), ["impersonator_id"], unique=False
        )
        batch_op.create_index(
            "ix_audit_outcome",
            ["outcome"],
            unique=False,
            postgresql_where=sa.text("outcome = 'failure'"),
        )
        batch_op.create_index(
            "ix_audit_reason_code",
            ["reason_code"],
            unique=False,
            postgresql_where=sa.text("reason_code IS NOT NULL"),
        )
        batch_op.create_index(
            "ix_audit_security_analysis",
            ["ip_address", "action", "outcome", "timestamp"],
            unique=False,
            postgresql_where=sa.text("severity IN ('warning', 'critical')"),
        )
        batch_op.create_index(
            "ix_audit_session_id",
            ["session_id"],
            unique=False,
            postgresql_where=sa.text("session_id IS NOT NULL"),
        )

    # 2. Alter audit_outbox
    with op.batch_alter_table("audit_outbox", schema=None) as batch_op:
        batch_op.alter_column(
            "processed", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "attempts", existing_type=sa.SMALLINT(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "failed", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
        )

    # 3. Alter users
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "failed_login_count",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )

    # 4. Enable Row Level Security (RLS)
    # Note: RLS on partitioned table applies to partitions.
    op.execute("ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY")
    # Policy: Allow inserts (Append-Only)
    op.execute("CREATE POLICY audit_logs_append_only ON audit_logs FOR INSERT WITH CHECK (true)")
    # Policy: Allow selects (Read-Only)
    op.execute("CREATE POLICY audit_logs_read_only ON audit_logs FOR SELECT USING (true)")
    # No policy for UPDATE/DELETE implies partial denial (default deny unless superuser)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Disable RLS
    op.execute("DROP POLICY IF EXISTS audit_logs_read_only ON audit_logs")
    op.execute("DROP POLICY IF EXISTS audit_logs_append_only ON audit_logs")
    op.execute("ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "failed_login_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("0"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'active'::character varying"),
            existing_nullable=False,
        )

    with op.batch_alter_table("audit_outbox", schema=None) as batch_op:
        batch_op.alter_column(
            "failed",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "attempts",
            existing_type=sa.SMALLINT(),
            server_default=sa.text("'0'::smallint"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "processed",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("false"),
            existing_nullable=False,
        )

    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_audit_session_id", postgresql_where=sa.text("session_id IS NOT NULL")
        )
        batch_op.drop_index(
            "ix_audit_security_analysis",
            postgresql_where=sa.text("severity IN ('warning', 'critical')"),
        )
        batch_op.drop_index(
            "ix_audit_reason_code", postgresql_where=sa.text("reason_code IS NOT NULL")
        )
        batch_op.drop_index("ix_audit_outcome", postgresql_where=sa.text("outcome = 'failure'"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_impersonator_id"))
        batch_op.alter_column(
            "schema_version",
            existing_type=sa.SMALLINT(),
            server_default=sa.text("'1'::smallint"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "source",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'web'::character varying"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "actor_type",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'user'::character varying"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "success",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("true"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "severity",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'info'::character varying"),
            existing_nullable=False,
        )
        batch_op.drop_column("environment")
        batch_op.drop_column("service_version")
        batch_op.drop_column("reason_code")
        batch_op.drop_column("outcome")
        batch_op.drop_column("request_path")
        batch_op.drop_column("request_method")
        batch_op.drop_column("impersonator_id")

    # ### end Alembic commands ###
