"""Add DeepLUsage model

Revision ID: c6a393b59004
Revises: 1b0caf6177e4
Create Date: 2025-12-21 21:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6a393b59004"
down_revision: str | None = "1b0caf6177e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deepl_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_identifier", sa.String(length=255), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("character_limit", sa.Integer(), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deepl_usage_key_identifier"), "deepl_usage", ["key_identifier"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deepl_usage_key_identifier"), table_name="deepl_usage")
    op.drop_table("deepl_usage")
    # ### end Alembic commands ###
