"""revert_user_bool_defs_to_base

Revision ID: e2f6de9f1495
Revises: f89bef1bd1b5
Create Date: 2025-05-17 20:33:57.690388

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e2f6de9f1495"
down_revision: str | None = "f89bef1bd1b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
