"""Add api_key column to users

Revision ID: e51f74fe569f
Revises: 8ca55a47da71
Create Date: 2025-12-27 19:22:29.577076

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e51f74fe569f"
down_revision: str | None = "8ca55a47da71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("api_key", sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f("ix_users_api_key"), ["api_key"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_api_key"))
        batch_op.drop_column("api_key")

    # ### end Alembic commands ###
