"""remove_py_defaults_from_user_bools

Revision ID: f89bef1bd1b5
Revises: 03cc263fdbf7
Create Date: 2025-05-17 20:26:58.982148

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f89bef1bd1b5"
down_revision: str | None = "03cc263fdbf7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
