// frontend/src/features/auth/components/PasskeySettings.tsx
/**
 * Passkey Settings Component
 *
 * Allows users to register, view, rename, and delete passkeys.
 * Enhanced with comprehensive error mapping, auto-naming, and anti-lockout warnings.
 */

import { useState, useMemo } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Key,
  Plus,
  Loader2,
  Trash2,
  Pencil,
  Check,
  X,
  Smartphone,
  ShieldCheck,
  AlertTriangle,
} from "lucide-react";
import { UAParser } from "ua-parser-js";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { useAuthStore } from "@/store/authStore";
import { passkeyApi, isWebAuthnSupported, PasskeyInfo } from "../api/passkey";

// Comprehensive error mapping for better UX
const PASSKEY_ERROR_MESSAGES: Record<string, string> = {
  // WebAuthn DOMExceptions
  NotAllowedError: "Registration cancelled or not permitted by your browser",
  SecurityError: "Security verification failed. Please try again.",
  InvalidStateError: "This authenticator is already registered",
  NotSupportedError: "Passkeys are not supported in this browser",
  AbortError: "Operation was cancelled",
  TimeoutError: "Request timed out. Please try again.",

  // Backend API errors
  challenge_expired: "Session expired. Please start again.",
  challenge_not_found: "Session expired. Please start again.",
  credential_not_found: "Passkey not found",
  rate_limited: "Too many attempts. Please wait and try again.",
  rp_id_mismatch: "Configuration error. Please contact support.",
  origin_mismatch: "Configuration error. Please contact support.",
  REAUTH_REQUIRED: "Please verify your identity to continue",

  // Generic fallback
  default: "An error occurred. Please try again.",
};

// Generate friendly device name from user agent
function generatePasskeyName(): string {
  try {
    // UAParser is called as a function with user agent string
    const result = UAParser(navigator.userAgent);

    const os = result.os.name || "Device";
    const browser = result.browser.name || "Browser";

    return `${os} – ${browser}`;
  } catch {
    // Fallback if parsing fails
    const date = new Date().toLocaleDateString();
    return `Passkey ${date}`;
  }
}

export function PasskeySettings() {
  const queryClient = useQueryClient();
  const userId = useAuthStore((state) => state.user?.id);

  const [showRegisterDialog, setShowRegisterDialog] = useState(false);
  const [deviceName, setDeviceName] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editName, setEditName] = useState("");
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Auto-generate device name when dialog opens
  const autoGeneratedName = useMemo(() => generatePasskeyName(), []);

  // Check if WebAuthn is supported
  const webAuthnSupported = isWebAuthnSupported();

  // Fetch passkeys
  const { data: passkeyStatus, isLoading } = useQuery({
    queryKey: ["passkeys", userId],
    queryFn: passkeyApi.listPasskeys,
    enabled: webAuthnSupported,
  });

  // Register mutation
  const registerMutation = useMutation({
    mutationFn: (name: string) => passkeyApi.register(name),
    onSuccess: () => {
      setShowRegisterDialog(false);
      setDeviceName("");
      setError(null);
      queryClient.invalidateQueries({ queryKey: ["passkeys", userId] });
    },
    onError: (err: unknown) => {
      // Extract error code/name from various error shapes
      interface PasskeyErrorResponse {
        name?: string;
        message?: string;
        response?: {
          data?: {
            code?: string;
            detail?:
              | string
              | {
                  code?: string;
                  message?: string;
                };
          };
        };
      }

      const error = err as PasskeyErrorResponse;
      const errorName = error.name;
      const data = error.response?.data;
      const errorCode =
        typeof data?.detail === "object" ? data.detail.code : data?.code;

      // Try to map to user-friendly message
      const errorMessage =
        (errorName && PASSKEY_ERROR_MESSAGES[errorName]) ||
        (errorCode && PASSKEY_ERROR_MESSAGES[errorCode]) ||
        (typeof data?.detail === "object"
          ? data.detail.message
          : data?.detail) ||
        error.message ||
        PASSKEY_ERROR_MESSAGES.default;

      setError(errorMessage);
    },
  });

  // Rename mutation
  const renameMutation = useMutation({
    mutationFn: ({ id, name }: { id: string; name: string }) =>
      passkeyApi.renamePasskey(id, name),
    onSuccess: () => {
      setEditingId(null);
      setEditName("");
      queryClient.invalidateQueries({ queryKey: ["passkeys", userId] });
    },
  });

  // Delete mutation
  const deleteMutation = useMutation({
    mutationFn: passkeyApi.deletePasskey,
    onSuccess: () => {
      setDeleteConfirmId(null);
      queryClient.invalidateQueries({ queryKey: ["passkeys", userId] });
    },
  });

  const handleRegister = () => {
    setError(null);
    // Use auto-generated name if user didn't provide one
    const finalName = deviceName.trim() || autoGeneratedName;
    registerMutation.mutate(finalName);
  };

  const handleStartEdit = (passkey: PasskeyInfo) => {
    setEditingId(passkey.id);
    setEditName(passkey.device_name || "");
  };

  const handleSaveEdit = (id: string) => {
    if (editName.trim()) {
      renameMutation.mutate({ id, name: editName.trim() });
    }
  };

  const handleCancelEdit = () => {
    setEditingId(null);
    setEditName("");
  };

  // WebAuthn not supported
  if (!webAuthnSupported) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Key className="h-5 w-5 text-muted-foreground" />
            Passkeys
          </CardTitle>
          <CardDescription>
            Passwordless authentication with biometrics or security keys
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="p-4 bg-muted/50 border rounded-lg">
            <p className="text-sm text-muted-foreground">
              Your browser doesn&apos;t support passkeys. Please use a modern
              browser like Chrome, Safari, Firefox, or Edge.
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center p-8">
        <Loader2 className="h-6 w-6 animate-spin" role="progressbar" />
      </div>
    );
  }

  const passkeys = passkeyStatus?.passkeys || [];
  const isLastPasskey = passkeys.length === 1;

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Key className="h-5 w-5" />
          Passkeys
        </CardTitle>
        <CardDescription>
          Sign in with your fingerprint, face, or security key — no password
          needed
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Info Banner */}
        {passkeys.length === 0 && (
          <div className="p-4 bg-primary/5 border border-primary/20 rounded-lg">
            <div className="flex items-start gap-3">
              <ShieldCheck className="h-5 w-5 text-primary mt-0.5" />
              <div className="text-sm">
                <p className="font-medium">Enable passwordless login</p>
                <p className="text-muted-foreground mt-1">
                  Passkeys are more secure than passwords and let you sign in
                  with Touch ID, Face ID, Windows Hello, or a security key.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Passkey List */}
        {passkeys.length > 0 && (
          <div className="space-y-2">
            {passkeys.map((passkey) => (
              <div
                key={passkey.id}
                className="flex items-center justify-between p-3 border rounded-lg"
              >
                <div className="flex items-center gap-3">
                  <Smartphone className="h-5 w-5 text-muted-foreground" />
                  <div>
                    {editingId === passkey.id ? (
                      <div className="flex items-center gap-2">
                        <Input
                          value={editName}
                          onChange={(e) => setEditName(e.target.value)}
                          className="h-8 w-48"
                          autoFocus
                          onKeyDown={(e) => {
                            if (e.key === "Enter") handleSaveEdit(passkey.id);
                            if (e.key === "Escape") handleCancelEdit();
                          }}
                        />
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleSaveEdit(passkey.id)}
                          disabled={renameMutation.isPending}
                        >
                          <Check className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={handleCancelEdit}
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                    ) : (
                      <>
                        <p className="font-medium">
                          {passkey.device_name || "Passkey"}
                        </p>
                        <p className="text-xs text-muted-foreground">
                          Added{" "}
                          {passkey.created_at
                            ? new Date(passkey.created_at).toLocaleDateString()
                            : "Unknown"}
                          {passkey.last_used_at && (
                            <>
                              {" • Last used "}
                              {new Date(
                                passkey.last_used_at,
                              ).toLocaleDateString()}
                            </>
                          )}
                          {passkey.backup_state && " • Synced"}
                        </p>
                      </>
                    )}
                  </div>
                </div>
                {editingId !== passkey.id && (
                  <div className="flex items-center gap-1">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleStartEdit(passkey)}
                    >
                      <Pencil className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setDeleteConfirmId(passkey.id)}
                    >
                      <Trash2 className="h-4 w-4 text-red-500" />
                    </Button>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Add Passkey Button */}
        <Button
          onClick={() => setShowRegisterDialog(true)}
          className="w-full"
          variant={passkeys.length > 0 ? "outline" : "default"}
        >
          <Plus className="mr-2 h-4 w-4" />
          Add Passkey
        </Button>

        {/* Register Dialog */}
        <Dialog open={showRegisterDialog} onOpenChange={setShowRegisterDialog}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Add a Passkey</DialogTitle>
              <DialogDescription>
                Your browser will prompt you to authenticate with biometrics or
                a security key.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">
                  Device Name (optional)
                </label>
                <Input
                  value={deviceName}
                  onChange={(e) => setDeviceName(e.target.value)}
                  placeholder={`Default: "${autoGeneratedName}"`}
                />
                <p className="text-xs text-muted-foreground">
                  A friendly name to identify this passkey
                </p>
              </div>
              {error && <p className="text-sm text-red-500">{error}</p>}
            </div>
            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => {
                  setShowRegisterDialog(false);
                  setDeviceName("");
                  setError(null);
                }}
              >
                Cancel
              </Button>
              <Button
                onClick={handleRegister}
                disabled={registerMutation.isPending}
              >
                {registerMutation.isPending && (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                )}
                Continue
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Delete Confirmation Dialog with Anti-Lock Warning */}
        <Dialog
          open={deleteConfirmId !== null}
          onOpenChange={(open) => !open && setDeleteConfirmId(null)}
        >
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Delete Passkey?</DialogTitle>
              <DialogDescription>
                {deleteConfirmId &&
                  passkeys.find((p) => p.id === deleteConfirmId)
                    ?.device_name && (
                    <span className="block mb-2">
                      &ldquo;
                      {
                        passkeys.find((p) => p.id === deleteConfirmId)
                          ?.device_name
                      }
                      &rdquo;
                    </span>
                  )}
                This passkey will be removed from your account. You can always
                add it again later.
              </DialogDescription>
            </DialogHeader>
            {/* Anti-lockout warning */}
            {isLastPasskey && (
              <div className="flex items-start gap-2 p-3 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-900 rounded-md">
                <AlertTriangle className="h-5 w-5 text-amber-600 dark:text-amber-500 flex-shrink-0 mt-0.5" />
                <div className="text-sm">
                  <p className="font-medium text-amber-900 dark:text-amber-100">
                    This is your only passkey
                  </p>
                  <p className="text-amber-700 dark:text-amber-300 mt-1">
                    You can still sign in with your password after deleting
                    this.
                  </p>
                </div>
              </div>
            )}
            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => setDeleteConfirmId(null)}
              >
                Cancel
              </Button>
              <Button
                variant="destructive"
                onClick={() =>
                  deleteConfirmId && deleteMutation.mutate(deleteConfirmId)
                }
                disabled={deleteMutation.isPending}
              >
                {deleteMutation.isPending && (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                )}
                Delete
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </CardContent>
    </Card>
  );
}
